development:
  adapter: postgresql
  database: greenfield-friendships-development
test:
  adapter: postgresql
  database: greenfield-friendships-test
production:
  adapter: postgresql
  database: greenfield-friendships-production